const { authenticateRequest } = require('../utils/supabase');
const { callGemini } = require('../utils/gemini');

module.exports = async function handler(req, res) {
  // CORS headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    await authenticateRequest(req);
  } catch (authErr) {
    console.error('[qa-engine] Authentication failure:', authErr.message);
    return res.status(authErr.status || 401).json({ success: false, error: authErr.message });
  }

  const {
    draftLetter,
    resumeText,
    jobTitle,
    companyName,
    jobDescription,
    hiringManager,
    location,
    clarifications // If user answered previous clarification questions
  } = req.body || {};

  if (!draftLetter) {
    return res.status(400).json({ error: 'Missing draftLetter for QA' });
  }

  try {
    const qaPrompt = `You are a strict, professional Quality Assurance (QA) Engine for a Cover Letter generation system.
Your job is to review the provided cover letter draft against the following 13-point checklist and ensure it is flawless.

========================================================
QA VALIDATION CHECKLIST
========================================================
1. HEADER VALIDATION: Must include Name, Email, Phone, Location.
2. DATE VALIDATION: Exactly ONE date exists. No duplicates.
3. SALUTATION VALIDATION: "Dear [Name]," or "Dear Hiring Manager," with correct capitalization.
4. GRAMMAR VALIDATION: Correct all tense errors, subject-verb disagreements, punctuation, etc., while preserving meaning.
5. FACTUAL CONSISTENCY: Cross-check against the provided Resume/Job Info. Do not invent facts. 
6. CONTACT CONSISTENCY: Ensure header matches any contact info in the text.
7. WATERMARK VALIDATION: Remove any "Generated by AI", "CareerCraft", or developer comments.
8. METRIC VALIDATION: Vague claims should be grounded in resume data. Don't invent numbers.
9. PROFESSIONAL TONE: Remove AI clichés ("I am thrilled", "delve into"). Use concise, natural language.
10. READABILITY: Break up walls of text (target 3-6 lines per paragraph).
11. ATS VALIDATION: Maintain natural language while ensuring keywords are present without stuffing.
12. LEGAL STYLE VALIDATION: If applicable, use formal tone. No informal expressions.
13. NO PLACEHOLDERS: Replace any [Insert Date] or [Company Name] with actual values if known, or rewrite sentence if unknown.

========================================================
CONTEXT
========================================================
Target Job: ${jobTitle || 'N/A'}
Target Company: ${companyName || 'N/A'}
Hiring Manager: ${hiringManager || 'N/A'}
Location: ${location || 'N/A'}

Resume Data:
${resumeText || 'None provided'}

User Clarifications (if any):
${clarifications ? JSON.stringify(clarifications) : 'None'}

Draft Letter:
${draftLetter}

========================================================
TASK
========================================================
Evaluate the draft.
If you find grammatical, formatting, or safe-to-fix issues, fix them automatically in the \`validatedLetter\`.
If you find CONFLICTING factual information (e.g., date mismatch, missing mandatory facts that you cannot infer), and you CANNOT safely resolve it, set \`status\` to "NEEDS_CLARIFICATION" and populate \`clarificationQuestions\`.
Otherwise, set \`status\` to "PASS".

Return ONLY a valid JSON object in this format:
{
  "status": "PASS" | "NEEDS_CLARIFICATION",
  "validatedLetter": "The fully corrected cover letter text.",
  "issues": [
    { "type": "GRAMMAR", "description": "Fixed comma splice in paragraph 2", "autoFixed": true }
  ],
  "clarificationQuestions": [
    { "id": "q1", "question": "The resume lists graduation in 2020 but the draft says 2021. Which is correct?" }
  ],
  "qaScore": 95
}
Do not include any markdown fences or explanation outside the JSON.`;

    const rr = await callGemini({
      contents: [{ parts: [{ text: qaPrompt }] }],
      generationConfig: { temperature: 0.2, maxOutputTokens: 2048 } // Low temp for QA
    });

    if (!rr.ok) throw new Error('AI QA failed');
    const rResult = await rr.json();
    let text = rResult?.candidates?.[0]?.content?.parts?.[0]?.text || '';
    
    // Clean JSON
    text = text.replace(/```json\s*/gi, '').replace(/```\s*/g, '').trim();
    
    let qaData;
    try {
      qaData = JSON.parse(text);
    } catch (e) {
      console.error('[qa-engine] JSON parse error:', e.message, text);
      return res.status(500).json({ error: 'Failed to parse QA results.' });
    }

    return res.status(200).json(qaData);

  } catch (error) {
    console.error('[qa-engine] Error:', error);
    return res.status(500).json({ error: 'Internal server error processing QA request.' });
  }
};
